Iterating

diff --git a/.github/workflows/semver.yaml b/.github/workflows/semver.yaml
--- a/.github/workflows/semver.yaml
+++ b/.github/workflows/semver.yaml
@@ -32,6 +32,18 @@ jobs:
             echo "$file was changed"
           done
 
+      - name: Ensure CHANGES.md has been changed
+        if: ! contains(steps.changed-files.outputs.all_changed_files, 'CHANGES.md')
+        run: |
+          echo "::error::CHANGES.md needs updating"
+          exit 1
+
+      - name: Ensure pack.yaml has been changed
+        if: ! contains(steps.changed-files.outputs.all_changed_files, 'pack.yaml')
+        run: |
+          echo "::error::pack.yaml needs updating"
+          exit 1
+
       # - name: Ensure CHANGELOG.md changed
       #   uses: Zomzog/changelog-checker@v1.3.0 # https://github.com/marketplace/actions/changelog-checker
       #   with:
